website/views.py
from flask import Flask, Blueprint, render_template, request, url_for, redirect, jsonify, flash, session
from flask_mail import Mail, Message
from flask import current_app as app
from website import mail  
from io import BytesIO
import os
import threading
from weasyprint import HTML
from bson.objectid import ObjectId
# from main import app
from website.commands import AddManagerCommand, DeleteManagerCommand, EditManagerCommand, Command

from website.models import db, admins, managers, clients, cars, reservations, client

from website.repository import ManagerRepository, CarRepository, ResRepository

from website.facade import CarRentalFacade

from concurrent.futures import ThreadPoolExecutor

from website.threads_tasks import send_email_in_background, save_data_in_background 

executor = ThreadPoolExecutor(5)

views = Blueprint('views', __name__)

# client = MongoClient('localhost', 27017)
# db = client.RentCars_db # creating your flask database using your mongo client 
# # collections
# admins = db.admins
# managers = db.managers
# clients = db.clients
# reservations = db.reservations
# cars = db.cars


# @views.route('/adminDashboard')
# def adminHome():
#     user_data = session.get('user_data')
#     if not user_data:
#         redirect(url_for("views.signin"))
#     # Fetch all managers from MongoDB
#     all_managers = managers.find()
    
#     # Count the number of managers
#     manager_count = managers.count_documents({})
#     car_count = cars.count_documents({})
#     reservation_count = reservations.count_documents({})
    
#     # Pass the managers data and manager count to the template
#     return render_template("AdminDashboard.html", managers=all_managers, manager_count=manager_count, user_data=user_data, car_count=car_count, reservation_count=reservation_count)

# def send_email_in_background(app, msg):
#     with app.app_context():
#         try:
#             mail.send(msg)
#             print("Email sent successfully!")
#         except Exception as e:
#             print(f"Failed to send email: {e}")


@views.route('/adminDashboard')
def adminHome():
    user_data = session.get('user_data')
    if not user_data:
        redirect(url_for("views.signin"))

    car_rental_facade = CarRentalFacade()
    all_managers = list(car_rental_facade.get_all_managers())
    all_cars = list(car_rental_facade.get_all_cars())
    all_res = list(car_rental_facade.get_all_reservations())

    manager_count = len(all_managers)
    car_count = len(all_cars)
    reservation_count = len(all_res)

    return render_template("AdminDashboard.html", managers=all_managers, manager_count=manager_count, user_data=user_data, car_count=car_count, reservation_count=reservation_count)


# @views.route('/adminDashboard')
# def adminHome():
#     user_data = session.get('user_data')
#     if not user_data:
#         redirect(url_for("views.signin"))

#     # Instantiate ManagerRepository
#     manager_repository = ManagerRepository()
#     car_repository = CarRepository()
#     res_repository = ResRepository()
#     # Fetch all managers from the repository
#     all_managers = manager_repository.get_all_managers()
#     all_cars = car_repository.get_all_cars()
#     all_res = res_repository.get_all_reservations()

#     # Count the number of managers
#     manager_count = manager_repository.collection.count_documents({})
#     car_count = car_repository.collection.count_documents({})
#     reservation_count = res_repository.collection.count_documents({})

#     # Pass the managers data and manager count to the template
#     return render_template("AdminDashboard.html", managers=all_managers, manager_count=manager_count, user_data=user_data, car_count=car_count, reservation_count=reservation_count)

@views.route('/profile')
def profile():
    user_id = request.args.get('id')
    # Assuming you have a way to identify the logged-in admin, fetch their details
    admin = admins.find_one({'_id': ObjectId(user_id)})  # Modify with your actual logic
    
    # Pass the admin's data to the template
    return render_template('editProfil.html', admin=admin)

@views.route('/managerDashboard')
def managerHome():
    user_data = session.get('user_data')
    if not user_data:
        redirect(url_for("views.signin"))

    all_cars = db.cars.find()

    return render_template("ManagerDashboard.html", user_data=user_data, cars=all_cars, filter={'category':'all','status':'all'})


@views.route('/', methods=['GET', 'POST'])
def signin():
    error_message = None  # Initialize error_message as None initially

    if request.method == "POST":
        sign_email = request.form['sign_email']
        sign_password = request.form['sign_password']
        sign_profile = request.form['sign_profile']

        # print(sign_email)
        # print(user['email'])
        # print(sign_profile)
        # print(user['profile'])

        if sign_profile == "Admin":
            admin = admins.find_one({'email': sign_email})
            if admin and admin['password'] == sign_password:
                session['user_data'] = {
                    'name': admin["name"],
                    'id': str(admin["_id"]),
                    'email': admin["email"]
                }
                return redirect(url_for('views.adminHome'))
            elif admin and admin['password'] != sign_password:
                # error_message = "Incorrect password. Please try again."
                flash("Incorrect password. Please try again.", "danger")
            else:
                # error_message = "Incorrect profile. Please try again."
                flash("Incorrect profile. Please try again.", "danger")
        
        elif sign_profile == "Manager":
            manager = managers.find_one({'email': sign_email})
            if manager and manager['password'] == sign_password:
                return redirect(url_for('views.managerHome'))
            elif manager and manager['password'] != sign_password:
                # error_message = "Incorrect password. Please try again."
                flash("Incorrect password. Please try again.", "danger")
            else:
                # error_message = "Incorrect profile. Please try again."
                flash("Incorrect profile. Please try again.", "danger")

    # Pass error_message to the template when rendering it
    return render_template('NewSignin.html')

@views.route('/registre', methods=('GET', 'POST'))
def registre():
    
    if request.method == "POST":   # if the request method is post, then insert the todo document in todos collection
        name = request.form['fullname']
        phone = request.form['phone']
        email = request.form['email']
        address = request.form['address']
        profile = request.form['profile']
        password = request.form['password']
        passwordCheck = request.form['passwordCheck']
        
        if profile == "Admin":
            admins.insert_one({'name': name, 
                            'phone': phone, 
                            'email': email, 
                            'address': address, 
                            'profile': profile, 
                            'password': password, 
                            'passwordCheck': passwordCheck})
            flash("Admin saved successfully!", "success")
            return redirect(url_for('views.signin')) # redirect the user to home page
        
        elif profile == "Manager":
            managers.insert_one({'name': name, 
                            'phone': phone, 
                            'email': email, 
                            'address': address, 
                            'profile': profile, 
                            'password': password, 
                            'passwordCheck': passwordCheck})
            flash("Manager saved successfully!", "success")
            return redirect(url_for('views.signin'))

    # Pass `feedback` to the template
    feedback = {'type': 'register', 'data': {'firstname': ''}}
    return render_template("NewRegistre.html", feedback=feedback)

def manager_handler(request, cmd:Command, dest:str='/adminDashboard'):
    with app.app_context():
        if request.method == 'POST':
            ret = cmd.execute()
            if ret:
                flash("Operation Succeded", "success")
            else:
                flash("Operation Failed!", "danger")
            return redirect(dest)
        return "Method Not Allowed", 405

@views.route('/add_manager', methods=['POST'])
def add_manager():
    command = AddManagerCommand(request.form)
    return (manager_handler(request, command))

@views.route('/<string:id>/delete_manager/', methods=['POST'])
def delete_manager(id):
    command = DeleteManagerCommand(id)
    return (manager_handler(request, command))

@views.route('/<string:id>/edit_manager/', methods=['POST'])
def edit_manager(id):
    command = EditManagerCommand(id, request.form)
    return (manager_handler(request, command))


# @views.route('/add_manager', methods=['POST'])
# def add_manager():
#     if request.method == 'POST':
#         name = request.form['name']
#         email = request.form['email']
#         address = request.form['address']
#         phone = request.form['phone']
#         password = request.form['password']
#         password_check = request.form['passwordCheck']

#         # Check if password matches passwordCheck
#         if password != password_check:
#             flash("Passwords do not match. Please try again.", "danger")
#             return redirect(url_for("views.adminHome"))

#         # Check if password meets minimum length requirement
#         if len(password) < 6:
#             flash("Password must be at least 6 characters long. Please try again.", "danger")
#             return redirect(url_for("views.adminHome"))

#         # Create a new manager document
#         new_manager = {
#             'name': name,
#             'email': email,
#             'phone': phone,

website/templates/NewRegistre.html
<!DOCTYPE html>
    <html>
        <head>
          <meta charset="utf-8">
          <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='registre.css')}}">
        </head>
        
        <body>
          <div class="login-root">
            <div class="box-root flex-flex flex-direction--column" style="min-height: 100vh;flex-grow: 1;">
              <div class="loginbackground box-background--white padding-top--64">
                <div class="loginbackground-gridContainer">
                  <div class="box-root flex-flex" style="grid-area: top / start / 8 / end;">
                    <div class="box-root" style="background-image: linear-gradient(white 0%, rgb(247, 250, 252) 33%); flex-grow: 1;">
                    </div>
                  </div>
                  <div class="box-root flex-flex" style="grid-area: 4 / 2 / auto / 5;">
                    <div class="box-root box-divider--light-all-2 animationLeftRight tans3s" style="flex-grow: 1;"></div>
                  </div>
                  <div class="box-root flex-flex" style="grid-area: 6 / start / auto / 2;">
                    <div class="box-root box-background--blue800" style="flex-grow: 1;"></div>
                  </div>
                  <div class="box-root flex-flex" style="grid-area: 7 / start / auto / 4;">
                    <div class="box-root box-background--blue animationLeftRight" style="flex-grow: 1;"></div>
                  </div>
                  <div class="box-root flex-flex" style="grid-area: 8 / 4 / auto / 6;">
                    <div class="box-root box-background--gray100 animationLeftRight tans3s" style="flex-grow: 1;"></div>
                  </div>
                  <div class="box-root flex-flex" style="grid-area: 2 / 15 / auto / end;">
                    <div class="box-root box-background--cyan200 animationRightLeft tans4s" style="flex-grow: 1;"></div>
                  </div>
                  <div class="box-root flex-flex" style="grid-area: 3 / 14 / auto / end;">
                    <div class="box-root box-background--blue animationRightLeft" style="flex-grow: 1;"></div>
                  </div>
                  <div class="box-root flex-flex" style="grid-area: 4 / 17 / auto / 20;">
                    <div class="box-root box-background--gray100 animationRightLeft tans4s" style="flex-grow: 1;"></div>
                  </div>
                  <div class="box-root flex-flex" style="grid-area: 5 / 14 / auto / 17;">
                    <div class="box-root box-divider--light-all-2 animationRightLeft tans3s" style="flex-grow: 1;"></div>
                  </div>
                </div>
              </div>
              <div class="box-root padding-top--24 flex-flex flex-direction--column" style="flex-grow: 1; z-index: 9;">
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                                {{ message }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
                <div class="box-root padding-top--48 padding-bottom--24 flex-flex flex-justifyContent--center">
                  <h1><a rel="dofollow">CarRental</a></h1>
                </div>
                <div class="formbg-outer">
                  <div class="formbg">
                    <div class="formbg-inner padding-horizontal--48">
                      <span class="padding-bottom--15">Sign in to your account</span>
                      <!-- <template id="registerTemplate"> -->
                        <form method="post"  id='stripe-login'>
                        <div class="field padding-bottom--24">
                            <label for="name">Full Name</label>
                            <input type="name" name="fullname" id='fullname' placeholder="Enter your full name">
                          </div>
                          <div class="field padding-bottom--24">
                            <label for="phone">Phone Number</label>
                            <input type="phone" name="phone" id='phone' placeholder="Enter your phone number "  >
                          </div>
                        <div class="field padding-bottom--24">
                          <label for="email">Email</label>
                          <input type="email" name="email" id="email" placeholder="exemple@gmail.com">
                        </div>
                        <div class="field padding-bottom--24">
                            <label for="address">Address</label>
                            <input type="text" name="address" id='address' placeholder="Enter your Detailed Adresse">
                          </div>
                          <div class="field padding-bottom--24">
                            <label for="profile">Profile</label>
                            <select name="profile" id="profile" class="profile-select">
                                <option value="" disabled selected></option>
                                <option value="Admin">Admin</option>
                                <option value="Manager">Manager</option>
                            </select>
                          </div>
                          
                          
                        <div class="field padding-bottom--24">
                          <div class="grid--50-50">
                            <label for="password">Password</label>
                            <div class="reset-pass">
                            </div>
                          </div>
                          <input type="password" name="password" id="password" placeholder="********">
                        </div>
                        <div class="field padding-bottom--24">
                            <div class="grid--50-50">
                              <label for="passwordCheck">Retype Password</label>
                              <div class="reset-pass">
                              </div>
                            </div>
                            <input type="password" name="passwordCheck" id='passwordcheck' placeholder="********">
                          </div>
                        <div class="field padding-bottom--24">
                            {% if error_message %}
                                <p class="msg_error">{{ error_message }}</p>
                            {% endif %}
                            <input :disabled='!isFormValid' type="submit" value="Sign in">
                        </div>
                      </form>
                      <!-- </template> -->
                    </div>
                  </div>
                  <div class="footer-link padding-top--24">
                    <span>Already have an account? <a href="{{ url_for('views.signin') }}">Sign in</a></span>
                    <div class="listing padding-top--24 padding-bottom--24 flex-flex center-center">
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </body>

          <script>
            document.addEventListener("DOMContentLoaded", function () {
              const profileSelect = document.getElementById("profile-select");
              const additionalFields = document.getElementById("additional-fields");
          
              profileSelect.addEventListener("change", function () {
                if (profileSelect.value === "student") {
                  additionalFields.style.display = "block";
                } else {
                  additionalFields.style.display = "none";
                }
              });
            });
          </script>
          <script>
            // Close the alert message when the close button (X) is clicked
            document.querySelectorAll('.alert .close').forEach(function(button) {
              button.addEventListener('click', function() {
                this.parentElement.style.display = 'none'; // Hide the parent alert element
              });
            });
          </script>
          

        </html>
    

website/templates/NewSignin.html
<!DOCTYPE html>
    <html>
        <head>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/css/bootstrap.min.css" rel="stylesheet">
          <link rel="stylesheet" href="{{ url_for('static', filename='login.css') }}">
        </head>
        
        <body>
            
          <div class="login-root">
            <div class="box-root flex-flex flex-direction--column" style="min-height: 100vh;flex-grow: 1;">
              <div class="loginbackground box-background--white padding-top--64">
                <div class="loginbackground-gridContainer">
                  <div class="box-root flex-flex" style="grid-area: top / start / 8 / end;">
                    <div class="box-root" style="background-image: linear-gradient(white 0%, rgb(247, 250, 252) 33%); flex-grow: 1;">
                    </div>
                  </div>
                  <div class="box-root flex-flex" style="grid-area: 4 / 2 / auto / 5;">
                    <div class="box-root box-divider--light-all-2 animationLeftRight tans3s" style="flex-grow: 1;"></div>
                  </div>
                  <div class="box-root flex-flex" style="grid-area: 6 / start / auto / 2;">
                    <div class="box-root box-background--blue800" style="flex-grow: 1;"></div>
                  </div>
                  <div class="box-root flex-flex" style="grid-area: 7 / start / auto / 4;">
                    <div class="box-root box-background--blue animationLeftRight" style="flex-grow: 1;"></div>
                  </div>
                  <div class="box-root flex-flex" style="grid-area: 8 / 4 / auto / 6;">
                    <div class="box-root box-background--gray100 animationLeftRight tans3s" style="flex-grow: 1;"></div>
                  </div>
                  <div class="box-root flex-flex" style="grid-area: 2 / 15 / auto / end;">
                    <div class="box-root box-background--cyan200 animationRightLeft tans4s" style="flex-grow: 1;"></div>
                  </div>
                  <div class="box-root flex-flex" style="grid-area: 3 / 14 / auto / end;">
                    <div class="box-root box-background--blue animationRightLeft" style="flex-grow: 1;"></div>
                  </div>
                  <div class="box-root flex-flex" style="grid-area: 4 / 17 / auto / 20;">
                    <div class="box-root box-background--gray100 animationRightLeft tans4s" style="flex-grow: 1;"></div>
                  </div>
                  <div class="box-root flex-flex" style="grid-area: 5 / 14 / auto / 17;">
                    <div class="box-root box-divider--light-all-2 animationRightLeft tans3s" style="flex-grow: 1;"></div>
                  </div>
                </div>
                
              </div>
              
              <div class="box-root padding-top--24 flex-flex flex-direction--column" style="flex-grow: 1; z-index: 9;">
                {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                                {{ message }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
                <div class="box-root padding-top--48 padding-bottom--24 flex-flex flex-justifyContent--center">
                  <h1><a  rel="dofollow">CarRental</a></h1>
                </div>
                <div class="formbg-outer">
                  <div class="formbg">
                    <div class="formbg-inner padding-horizontal--48">
                      <span class="padding-bottom--15">Sign in to your account</span>
                      <form method="post" id="stripe-login">
                        <div class="field padding-bottom--24">
                          <label for="email">Email</label>
                          <input type="email" name="sign_email" type="email" id='email' placeholder="example@gmail.com">
                        </div>
                        <div class="field padding-bottom--24">
                          <label for="profile">Profile</label>
                          <select name="sign_profile" id='profile' class="profile-select">
                            <option value="" disabled selected></option>
                            <option value="Admin">Admin</option>
                            <option value="Manager">Manager</option>
                          </select>
                        </div>

                        <div class="field padding-bottom--24">
                            <label for="password">Password</label>
                            <input type="password" name="sign_password" type="password" id='password' placeholder="enter your password">
                        </div>

                        <div class="field padding-bottom--24">
                            {% if error_message %}
                                <p class="msg_error">{{ error_message }}</p>
                            {% endif %}
                            <input :disabled='!isFormValid' type="submit" value="Sign in">
                        </div>

                      </form>
                    </div>
                  </div>
                  <div class="footer-link padding-top--24">
                    <span>Don't have an account? <a href="{{ url_for('views.registre') }}">Registre</a></span>
                    <div class="listing padding-top--24 padding-bottom--24 flex-flex center-center">
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>



          <script>
            // Close the alert message when the close button (X) is clicked
            document.querySelectorAll('.alert .close').forEach(function(button) {
              button.addEventListener('click', function() {
                this.parentElement.style.display = 'none'; // Hide the parent alert element
              });
            });
          </script>
        </body>
        
        </html>
    

website/templates/signin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <title>Your Title</title>
    
    <!-- Link your CSS file -->
    <link rel="stylesheet" href="{{ url_for('static', filename='RegistreLogin.css') }}">
</head>
<body>
    <div id="app" v-cloak>

        <div class="actions">
            <a href="{{ url_for('views.registre') }}">
              <button>Register</button>
            </a>
            <a href="">
                <button :class='[{ active: isDisabled("signin") }]'
                @click.prevent='setComponent("signin")'>Sign in</button>
            </a>
        </div>

        
        <transition name='form' mode='out-in'>
            <keep-alive>
                <component :feedback='feedback' :is="currentComponent"
                @register-form='handleForm' @signin-form='handleForm'></component>
            </keep-alive>
        </transition>
        
        

    </div>
    {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
            {% for category, message in messages %}
              <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
            {% endfor %}
    {% endif %}
    {% endwith %}

    <!-- Signin Template -->
    <template id="signinTemplate">
        <form ref='form' method="post" action="{{ url_for('views.signin') }}" class='signin-form'>
            <h2>Sign in</h2>
            <div class="form-group">
                <label for="email">Email </label>
                <input required v-model='user.email' name="sign_email" type="email" id='email' placeholder="example@gmail.com">
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input required v-model='user.password' name="sign_password" type="password" id='password' placeholder="enter your password">
            </div>
            <div class="form-group">
                <label for="profile">Profile</label>
                <div class="select-wrapper">
                    <span class="placeholder" v-show="!user.profile">Select your matched profile</span>
                    <select required v-model='user.profile' name="sign_profile" id='profile'>
                        <option value="Admin">Admin</option>
                        <option value="Manager">Manager</option>
                    </select>
                </div>
            </div>
            <div class="cont">
                {% if error_message %}
                <p class="msg_error">{{ error_message }}</p>
            {% endif %}
                <input :disabled='!isFormValid' type="submit" value="Sign in">
            </div>
        </form>
    </template>

    <script src="https://cdn.jsdelivr.net/npm/vue@2"></script>
    <script src="{{ url_for('static', filename='signin.js') }}"></script>  
    
    <script data-cfasync="false" src="/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
    <script>
        // Close the alert message when the close button (X) is clicked
        document.querySelectorAll('.alert .close').forEach(function(button) {
          button.addEventListener('click', function() {
            this.parentElement.style.display = 'none'; // Hide the parent alert element
          });
        });
      </script>
</body>

</html>